import type { CharacterDef, CharacterKey } from '../types'

// 主角 + 解鎖角色，每個有獨特開局 stat / starting skill。
// Card style 仿古惑仔手遊：rarity（XR > SSR > SR > R）+ 職業（攻/防/智/醫/輔）+ 5 星 + 戰力。
export const CHARACTERS: Record<CharacterKey, CharacterDef> = {
  chan_ho_nam: {
    key: 'chan_ho_nam',
    displayName: '陳浩南',
    english: 'Chan Ho-nam',
    rarity: 'XR',
    classType: 'attack',
    stars: 5,
    battlePower: 17640,
    unlockReq: 0,
    description: '銅鑼灣揸 fit 人，全能型，西瓜刀 + 撼到正。',
    tagline: '出嚟行，遲早要還',
    baseStats: {
      damage: 16,
      critChance: 0.10,
      critMult: 1.7,
    },
    startingSkills: ['crit'],
    portraitColor: '#e84a52',
    silhouette: 'lean',
  },
  shan_gai: {
    key: 'shan_gai',
    displayName: '山雞',
    english: 'Shan Gai',
    rarity: 'XR',
    classType: 'attack',
    stars: 5,
    battlePower: 16029,
    unlockReq: 5,
    description: '快手快腳，攻速高但血薄。',
    tagline: '我山雞唔係好惹㗎',
    baseStats: {
      maxHp: 80,
      hp: 80,
      attackRate: 3.2,
      speed: 260,
    },
    startingSkills: ['attackSpeed'],
    portraitColor: '#ff7a2e',
    silhouette: 'punk',
  },
  wu_ngaa_player: {
    key: 'wu_ngaa_player',
    displayName: '烏鴉',
    english: 'Wu Ngaa',
    rarity: 'XR',
    classType: 'wisdom',
    stars: 5,
    battlePower: 15829,
    unlockReq: 12,
    description: '專插冷子，預設過骨 + 暴擊。',
    tagline: '殺人放火金腰帶',
    baseStats: {
      damage: 18,
      critChance: 0.15,
    },
    startingSkills: ['pierce', 'crit'],
    portraitColor: '#a45cff',
    silhouette: 'cool',
  },
  liang_kun: {
    key: 'liang_kun',
    displayName: '靚坤',
    english: 'Liang Kun',
    rarity: 'SSR',
    classType: 'defense',
    stars: 4,
    battlePower: 14055,
    unlockReq: 20,
    description: '坦得驚人，慢但夠頂、有護盾。',
    tagline: '我食鹽多過你食米',
    baseStats: {
      maxHp: 150,
      hp: 150,
      speed: 200,
      shieldMaxStacks: 1,
    },
    startingSkills: ['shield'],
    portraitColor: '#f0a82e',
    silhouette: 'bulky',
  },
  tai_tin_yi: {
    key: 'tai_tin_yi',
    displayName: '大天二',
    english: 'Tai Tin-yi',
    rarity: 'SSR',
    classType: 'attack',
    stars: 5,
    battlePower: 13648,
    unlockReq: 35,
    description: '通關後解鎖。攻防一體，紅雞 + 飲血。',
    tagline: '我哋係兄弟',
    baseStats: {
      maxHp: 120,
      hp: 120,
      damage: 18,
      lifesteal: 3,
      rageMultMax: 0.5,
    },
    startingSkills: ['rage', 'lifesteal'],
    portraitColor: '#ffd16a',
    silhouette: 'fighter',
  },
  wong_mou_fu: {
    key: 'wong_mou_fu',
    displayName: '黃毛虎',
    english: 'Wong Mou Fu',
    rarity: 'SR',
    classType: 'attack',
    stars: 3,
    battlePower: 10078,
    unlockReq: 8,
    description: '黃毛少年，暴怒型。',
    tagline: '我邊度有得驚?',
    baseStats: {
      damage: 16,
      attackRate: 2.8,
    },
    startingSkills: ['damageUp'],
    portraitColor: '#ffe070',
    silhouette: 'wild',
  },
  siu_min_fu: {
    key: 'siu_min_fu',
    displayName: '笑面虎',
    english: 'Siu Min Fu',
    rarity: 'SR',
    classType: 'defense',
    stars: 3,
    battlePower: 10808,
    unlockReq: 15,
    description: '笑面背後鐵拳，反擊好強。',
    tagline: '係兄弟就唔好出聲',
    baseStats: {
      maxHp: 140,
      hp: 140,
      damage: 14,
    },
    startingSkills: ['shield'],
    portraitColor: '#ff8c66',
    silhouette: 'thug',
  },
  taai_zi: {
    key: 'taai_zi',
    displayName: '太子',
    english: 'Taai Zi',
    rarity: 'SR',
    classType: 'wisdom',
    stars: 3,
    battlePower: 10808,
    unlockReq: 18,
    description: '頭腦人，控場 + 元素 mix。',
    tagline: '一動不如一靜',
    baseStats: {
      damage: 14,
      freezeChance: 0.15,
      lightningChance: 0.15,
    },
    startingSkills: ['freeze', 'lightning'],
    portraitColor: '#9b6cff',
    silhouette: 'kid',
  },
  daai_lou_b: {
    key: 'daai_lou_b',
    displayName: '大佬B',
    english: 'Big Brother B',
    rarity: 'SSR',
    classType: 'support',
    stars: 4,
    battlePower: 6248,
    unlockReq: 25,
    description: '老一輩大佬，召喚馬仔頂上。',
    tagline: '叫晒兄弟出嚟',
    baseStats: {
      summonCount: 1,
    },
    startingSkills: ['summon'],
    portraitColor: '#a8709a',
    silhouette: 'oldschool',
  },
  fung_wan: {
    key: 'fung_wan',
    displayName: '風雲',
    english: 'Fung Wan',
    rarity: 'SSR',
    classType: 'attack',
    stars: 4,
    battlePower: 18771,
    unlockReq: 30,
    description: '風雲再起，火爆 + 流血雙元素。',
    tagline: '雷霆萬鈞',
    baseStats: {
      damage: 18,
      fireChance: 0.2,
      bleedChance: 0.2,
    },
    startingSkills: ['fire', 'bleed'],
    portraitColor: '#ff4d4d',
    silhouette: 'punk',
  },
}

export const ROSTER_ORDER: CharacterKey[] = [
  'chan_ho_nam',
  'shan_gai',
  'wu_ngaa_player',
  'liang_kun',
  'tai_tin_yi',
  'wong_mou_fu',
  'siu_min_fu',
  'taai_zi',
  'daai_lou_b',
  'fung_wan',
]
